NO_SENSORS = 40
SENSOR_MAX_POWER_MEAN = 0.15
SENSOR_MAX_POWER_STD_DEVIATION = 0
SENSOR_STATIC_POWER_MEAN = 0.007
SENSOR_STATIC_POWER_STD_DEVIATION = 0.001
SENSOR_CU_POWER_MEAN = 10
SENSOR_CU_STD_DEVIATION = 5

NO_SOLAR_MICROPROCESSORS = 5
NO_BAT_MICROPROCESSORS = 5
NO_GRID_MICROPROCESSORS = 5

MICROPROCESSORS_MAX_POWER_MEAN = 6.5
MICROPROCESSORS_MAX_POWER_STD_DEVIATION = 1.5
MICROPROCESSORS_STATIC_POWER_MEAN = 4.8
MICROPROCESSORS_STATIC_POWER_STD_DEVIATION = 1
MICROPROCESSORS_CU_POWER_MEAN = 45
MICROPROCESSORS_CU_STD_DEVIATION = 10

SERVER_POWER_PER_CU = 20e-3
SERVER_STATIC_POWER = 100

WIRED_BANDWIDTH_MEAN = 50e6
WIRED_BANDWIDTH_STD_DEVIATION = 10e6
WIRED_ENERGY_PER_BIT_MEAN = 0
WIRED_ENERGY_PER_BIT_STD_DEVIATION = 0

WIRELESS_BANDWIDTH_MEAN = 30e6
WIRELESS_BANDWIDTH_STD_DEVIATION = 5e5
WIRELESS_ENERGY_PER_BIT_MEAN = 400e-9
WIRELESS_ENERGY_PER_BIT_STD_DEVIATION = 50e-9
