
NO_SENSORS = 20
SENSOR_MAX_POWER_MEAN = 0.5e-3
SENSOR_MAX_POWER_STD_DEVIATION = 0.1e-3
SENSOR_STATIC_POWER_MEAN = 0.1e-3
SENSOR_STATIC_POWER_STD_DEVIATION = 0.5e-4
SENSOR_CU_POWER_MEAN = 10
SENSOR_CU_STD_DEVIATION = 5

NO_MICROPROCESSORS = 5
MICROPROCESSORS_MAX_POWER_MEAN = 2.5
MICROPROCESSORS_MAX_POWER_STD_DEVIATION = 0.5
MICROPROCESSORS_STATIC_POWER_MEAN = 0.8
MICROPROCESSORS_STATIC_POWER_STD_DEVIATION = 0.2
MICROPROCESSORS_CU_POWER_MEAN = 45
MICROPROCESSORS_CU_STD_DEVIATION = 10

SERVER_POWER_PER_CU = 20e-3
SERVER_STATIC_POWER = 100

WIRED_BANDWIDTH_MEAN = 10e6
WIRED_BANDWIDTH_STD_DEVIATION = 1e6
WIRED_ENERGY_PER_BIT_MEAN = 200e-6
WIRED_ENERGY_PER_BIT_STD_DEVIATION = 20e-6

WIRELESS_BANDWIDTH_MEAN = 5e6
WIRELESS_BANDWIDTH_STD_DEVIATION = 5e5
WIRELESS_ENERGY_PER_BIT_MEAN = 200e-9
WIRELESS_ENERGY_PER_BIT_STD_DEVIATION = 20e-9
